# Numpy

In [1]:
import numpy as np
# base package for pandas(panel data structure)
# numpy -- numerical python

In [2]:
# python calculations are slower than numpy
# Numpy uses the concept of vectorization
# Vectorization is the process of python code into c code

In [3]:
# Numpy limitations
# Numpy arrays are homogenous. List can be heterogenous
# Numpy arrays do not support all data types. List however supports all the data types
# Numpy array -- boolean indexing. List -- boolean indexing XXX
# Numpy array -- fancy indexing. List -- fancy indexing

# creating array


In [4]:
nums = np.array([1,2,3,5])

In [5]:
type(nums)
# ndarray -- n dimensional array

numpy.ndarray

In [6]:
matrix = np.array([[1,2,3,4],[5,6,7,8]])

In [7]:
matrix

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
type(matrix)

numpy.ndarray

In [9]:
# np.uint8 np.int8
# np.uint16 np.int16
# np.uint32 np.int32
# np.float16
# np.float32
# np.bool_

In [11]:
np.bool_(0)

False

In [12]:
np.array([1,2,3,4,5], dtype = 'bool')

array([ True,  True,  True,  True,  True])

In [13]:
np.array([1,2,34,5,56], dtype = np.bool_)

array([ True,  True,  True,  True,  True])

In [14]:
het = np.array([1,'Abhishek', 'Abhilash'])

In [15]:
het # useless

array(['1', 'Abhishek', 'Abhilash'], dtype='<U11')

# attributes

In [16]:
nums

array([1, 2, 3, 5])

In [17]:
nums.dtype

dtype('int32')

In [18]:
nums.size

4

In [19]:
nums.shape # tuple (4, )

(4,)

In [24]:
x = (4, )

type(x)

tuple

In [25]:
matrix

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [26]:
matrix.shape

(2, 4)

In [27]:
matrix.size

8

In [28]:
nums

array([1, 2, 3, 5])

In [29]:
nums.ndim

1

In [30]:
matrix.ndim

2

In [31]:
matrix.dtype

dtype('int32')

In [32]:
# ndim  --- len(shape)

[[[0.5488135  0.71518937 0.60276338 0.54488318]
  [0.4236548  0.64589411 0.43758721 0.891773  ]
  [0.96366276 0.38344152 0.79172504 0.52889492]]

 [[0.56804456 0.92559664 0.07103606 0.0871293 ]
  [0.0202184  0.83261985 0.77815675 0.87001215]
  [0.97861834 0.79915856 0.46147936 0.78052918]]]


0.4375872112626925

# creating arrays from iskrech(scratch)


In [41]:
np.zeros(3) # float

array([0., 0., 0.])

In [42]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [43]:
np.zeros((3,4), dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [44]:
np.zeros((5,6), dtype = np.bool_)

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [45]:
# ones

In [46]:
np.ones(3) # float

array([1., 1., 1.])

In [47]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [48]:
np.ones((3,4,5), dtype = np.bool_) # boolean tensor
# scalar -- 5,6
# 1D array -- [1,2,3], [4,5,6]
# 2D array -- matrix 
# 3D array -- tensor(machine learning)

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [49]:
np.full((3,4), 3.14)

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]])

In [50]:
from math import pi
np.full((2,5), pi, dtype = int)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [52]:
# range(low, high(exclusive), step)
list(range(1,10))
list(range(1,20,3))

[1, 4, 7, 10, 13, 16, 19]

In [53]:
nums = np.arange(1, 20, 2) # 1D array
nums

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [54]:
np.arange(1,20,2)
np.array(range(1,20,2))

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [58]:
np.eye(3,4) # eye function is used to create identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [59]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [63]:
np.eye(2,3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [64]:
np.linspace(1,10,num = 10, dtype = float)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [65]:
from math import pi

In [66]:
x = np.linspace(-2 * pi, 2 * pi, num = 10000)
x

array([-6.28318531, -6.28192854, -6.28067178, ...,  6.28067178,
        6.28192854,  6.28318531])

In [67]:
from math import sin

In [68]:
y = [sin(x_i) for x_i in x]

In [69]:
y

[2.4492935982947064e-16,
 0.0012567624068774398,
 0.0025135228287573833,
 0.003770279280648623,
 0.005027029777562426,
 0.006283772334523015,
 0.0075405049665644925,
 0.008797225688736632,
 0.01005393251611069,
 0.011310623463777196,
 0.012567296546851766,
 0.013823949780480897,
 0.01508058117983888,
 0.016337188760138056,
 0.017593770536625704,
 0.018850324524589877,
 0.020106848739365173,
 0.021363341196330553,
 0.02261979991091514,
 0.023876222898604017,
 0.025132608174935137,
 0.02638895375550957,
 0.02764525765598843,
 0.028901517892098647,
 0.030157732479638794,
 0.031413899434475985,
 0.03267001677255611,
 0.03392608250990079,
 0.03518209466261313,
 0.03643805124688352,
 0.03769395027898747,
 0.03894978977529139,
 0.04020556775225839,
 0.04146128222644519,
 0.042716931214512366,
 0.043972512733221246,
 0.04522802479943974,
 0.04648346543014812,
 0.047738832642436814,
 0.048994124453512214,
 0.05024933888070247,
 0.051504473941454396,
 0.05275952765334373,
 0.05401449803407202,
 

In [70]:
import matplotlib.pyplot as plt

In [71]:
%matplotlib inline

In [ ]:
plt.plot(x,y)
plt.s